Repository Discarded-Team/Pyndemic, pull requests merged in 2020-05, with the labels that each got.

#1 Release 0.1
  .gitattributes
  .gitignore
  .idea/Pandemic.iml
  .idea/dictionaries/joe.xml
  .idea/inspectionProfiles/profiles_settings.xml
  .idea/misc.xml
  .idea/modules.xml
  .idea/workspace.xml
  CHANGELOG.md
  LICENSE
  PandemicGame.py
  README.md
  assets/readme/game_screenshot_1.png
  pyndemic.py
  settings.cfg
  src/__init__.py
  src/api.py
  src/card.py
  src/city.py
  src/commands.py
  src/config.py
  src/controller.py
  src/deck.py
  src/disease.py
  src/exceptions.py
  src/game.py
  src/log.py
  src/player.py
  t_PandemicGame.py
  test/__init__.py
  test/test_api.py
  test/test_card.py
  test/test_city.py
  test/test_config.py
  test/test_controller.py
  test/test_deck.py
  test/test_disease.py
  test/test_game.py
  test/test_input.txt
  test/test_player.py
  test/test_settings.cfg
Labels: release

#4 Feature/disease cubes
  src/disease.py
  src/game.py
  src/player.py
  test/test_disease.py
  test/test_game.py
  test/test_player.py
Labels: improvement

#5 Feature/reduce settings usage
  settings.cfg
  src/city.py
  src/commands.py
  src/deck.py
  src/game.py
  test/test_city.py
  test/test_deck.py
  test/test_game.py
  test/test_settings.cfg
Labels: improvement

#6 Feature/code cleaning
  src/city.py
  src/game.py
  src/player.py
  test/test_city.py
  test/test_game.py
  test/test_player.py
Labels: refactoring

#7 Feature/infection levels
  settings.cfg
  src/city.py
  src/commands.py
  src/controller.py
  src/game.py
  src/player.py
  test/test_city.py
  test/test_disease.py
  test/test_game.py
  test/test_player.py
  test/test_settings.cfg
Labels: refactoring

#9 Feature/serialisation
  src/city.py
  src/formatter.py
  src/player.py
  test/test_card.py
  test/test_formatter.py
  test/test_player.py
Labels: improvement

#12 Coroutine game controller
  pyndemic.py
  src/controller.py
  test/test_controller.py
Labels: improvement

#14 Console user interface
  pyndemic.py
  src/ui/__init__.py
  src/ui/console.py
Labels: improvement

#17 Feature/add setup py
  setup.py
Labels: enhancement
