Repository Discarded-Team/Pyndemic, pull requests merged in 2020-07, with the labels that each got.

#26 Release 0.2 fix actions
  .github/workflows/main.yml
  requirements.txt
  test/__init__.py
  test/test_core/__init__.py
  test/test_ui/__init__.py
Labels: fix

#25 Release 0.2
  .github/workflows/main.yml
  .gitignore
  API.md
  CHANGELOG.md
  README.md
  assets/readme/game_screenshot_1.png
  doc/readme/game_screenshot_1.png
  pyndemic.py
  pyndemic/__init__.py
  pyndemic/card.py
  pyndemic/character.py
  pyndemic/city.py
  pyndemic/commands.py
  pyndemic/config.py
  pyndemic/controller.py
  pyndemic/core/__init__.py
  pyndemic/core/api.py
  pyndemic/core/context.py
  pyndemic/core/game_entity.py
  pyndemic/core/utils.py
  pyndemic/deck.py
  pyndemic/disease.py
  pyndemic/exceptions.py
  pyndemic/formatter.py
  pyndemic/game.py
  pyndemic/log.py
  pyndemic/settings.cfg
  pyndemic/ui/__init__.py
  pyndemic/ui/console.py
  pyndemic/ui/standard.py
  requirements.txt
  setup.py
  src/__init__.py
  src/api.py
  src/city.py
  src/commands.py
  src/controller.py
  src/disease.py
  src/game.py
  test/__init__.py
  test/test_api.py
  test/test_card.py
  test/test_character.py
  test/test_city.py
  test/test_commands.py
  test/test_config.py
  test/test_controller.py
  test/test_core/__init__.py
  test/test_core/test_api.py
  test/test_core/test_context.py
  test/test_core/test_game_entity.py
  test/test_deck.py
  test/test_disease.py
  test/test_formatter.py
  test/test_game.py
  test/test_input.txt
  test/test_player.py
  test/test_settings.cfg
  test/test_ui/__init__.py
  test/test_ui/test_console.py
Labels: release

#28 Card-oriented game logic improvements
  pyndemic/card.py
  pyndemic/core/context.py
  pyndemic/core/game_entity.py
  pyndemic/deck.py
  pyndemic/game.py
  test/test_card.py
  test/test_character.py
  test/test_commands.py
  test/test_controller.py
  test/test_core/test_context.py
  test/test_core/test_game_entity.py
  test/test_deck.py
  test/test_formatter.py
  test/test_game.py
  test/test_helpers.py
Labels: improvement

#29 Automatic version checking in the setup file.
  pyndemic.py
  pyndemic/__init__.py
  setup.py
Labels: enhancement

#30 Feature/action cards
  pyndemic/action_card.py
  pyndemic/card.py
  pyndemic/character.py
  pyndemic/deck.py
  pyndemic/formatter.py
  pyndemic/game.py
  test/test_action_card.py
  test/test_card.py
  test/test_character.py
  test/test_controller.py
  test/test_deck.py
  test/test_formatter.py
  test/test_game.py
Labels: enhancement, improvement
